{{- /*
=============================================================================
Portfolio Site - Service Account Template
Defines the service account for pod identity
=============================================================================
*/ -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "portfolio-site-chart.serviceAccountName" . }}
  labels:
    app: portfolio
    app.kubernetes.io/name: portfolio-site
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.serviceAccount.automount }}
automountServiceAccountToken: true
{{- else }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
